[tool.poetry]
name = "web3-ethereum-defi"
version = "0.7.1"
description = "Web3 Ethereum DeFi toolkit for smart contracts, Ethereum JSON-RPC utilities, Uniswap, PancakeSwap, wallets and automated test suites."
authors = ["Mikko Ohtamaa <mikko@tradingstrategy.ai>"]
license = "MIT"
homepage = "https://tradingstrategy.ai"
repository = "https://github.com/tradingstrategy-ai/web3-ethereum-defi"
readme = "README.md"
keywords = ["ethereum", "cryptocurrency", "uniswap", "erc-20", "pancakeswap", "sushiswap", "polygon", "web3", "blockchain"]
packages = [
    { include = "eth_defi" },
]

[tool.poetry.dependencies]
python = "^3.8"
web3 = {extras = ["tester"], version = "^5.28.0"}
Sphinx = {version = "^4.4.0", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}
sphinx-sitemap = {version = "^2.2.0", optional = true}
sphinx-autodoc-typehints = {version = "^1.16.0", extras = ["docs"], optional = true}
psutil = "^5.9.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
sphinx-rtd-theme = "^1.0.0"
sphinx-sitemap = "^2.2.0"
ipdb = "^0.13.9"
black = "^22.1.0"
flake8 = "^4.0.1"

# See discussion https://github.com/python-poetry/poetry/issues/3348#issuecomment-726534462
[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinx-sitemap", "sphinx-autodoc-typehints"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--capture=no --durations=0"

[tool.black]
line-length = 999

[tool.isort]
profile = "black"