name: Automated test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'poetry'
      - name: Install dependencies
        run: |
          poetry env use '3.9'
          poetry install
      - name: Install Ganache
        run: yarn global add ganache
      - name: Run flake8
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run test scripts
        run: poetry run pytest
        env:
          BNB_CHAIN_JSON_RPC: ${{ secrets.BNB_CHAIN_JSON_RPC }}
  test-compile-abi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Set up NodeJS 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: |
            contracts/sushiswap/yarn.lock
            contracts/uniswap-v3-core/yarn.lock
            contracts/uniswap-v3-periphery/yarn.lock
      - name: Cook sushi
        run: make copy-sushi-abi
      - name: Copy uniswap v3
        run: make copy-uniswapv3-abi